# Generated by Django 4.2.18 on 2025-01-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='total_score',
        ),
    ]
