# Generated by Django 4.2.18 on 2025-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating Count'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rate'),
        ),
    ]
