# Generated by Django 4.2.18 on 2025-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_rating_score_article_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.PositiveSmallIntegerField(verbose_name='Rate'),
        ),
    ]
